-- scripts/sql/0003_consolidate_themes.sql
-- One-shot data migration applied to the 0008 dump to produce the 0009 baseline.
-- Operations (single transaction):
--   1. INSERT the 10 new themes (slugs allocated fresh via gen_random_uuid()).
--   2. Reassign every poem from its old theme to the corresponding new theme
--      via a (new_name, old_name) VALUES mapping joined on themes.name.
--   3. DELETE the 27 legacy theme rows.
--
-- The 'عدل' theme (4 poems) was not in the original spec's old-theme list;
-- it is merged into 'الحكمة والآداب' per maintainer decision.
--
-- All views that join `themes` (theme_stats, theme_poems, poem_full_data, …)
-- are plain views, so no REFRESH is needed afterward.
--
-- NOT idempotent: re-running on already-migrated data raises an exception via
-- the pre-flight guard below.
BEGIN;

DO $$
DECLARE
  v_pre_themes_match   integer;
  v_pre_themes_total   integer;
  v_pre_poems_total    integer;
  v_post_poems_total   integer;
  v_orphans            integer;
BEGIN
  -- Pre-flight: assert the legacy 27-theme layout is present (26 from the
  -- consolidation spec + 'عدل' that lived in the dataset). If not, abort.
  SELECT count(*) INTO v_pre_themes_match
  FROM themes
  WHERE name IN (
    'قصيرة','عامة','مدح','رومنسية','هجاء','حزينة','عتاب','رثاء','غزل','دينية',
    'شوق','من','فراق','حكمة','ذم','نصيحة','وطن','صبر','ابتهال','أنشودة','جود',
    'غير مصنف','رحمة','معلقة','سياسية','اعتذار','عدل'
  );
  SELECT count(*) INTO v_pre_themes_total FROM themes;
  IF v_pre_themes_match <> 27 OR v_pre_themes_total <> 27 THEN
    RAISE EXCEPTION
      'pre-flight failed: expected exactly the 27 legacy theme rows, matched % of %',
      v_pre_themes_match, v_pre_themes_total;
  END IF;

  SELECT count(*) INTO v_pre_poems_total FROM poems;

  -- themes.id is `GENERATED BY DEFAULT AS IDENTITY` and pg_restore loaded the
  -- rows with explicit ids, so the backing sequence never advanced past the
  -- restored max. Push it forward before the next default-allocated INSERT,
  -- otherwise it tries id=1 and collides with an existing row.
  PERFORM setval(pg_get_serial_sequence('themes', 'id'),
                 (SELECT coalesce(max(id), 0) FROM themes));

  -- (1) Insert the 10 new themes. Slugs are fresh uuids — no legacy URL to
  -- preserve, since the old theme slugs are being removed.
  INSERT INTO themes (name, slug) VALUES
    ('المديح',                   gen_random_uuid()),
    ('الفخر والحماسة',           gen_random_uuid()),
    ('الهجاء',                   gen_random_uuid()),
    ('الرثاء',                   gen_random_uuid()),
    ('النسيب والغزل',            gen_random_uuid()),
    ('العتاب والاعتذار',         gen_random_uuid()),
    ('الحكمة والآداب',           gen_random_uuid()),
    ('الزهد والمناجاة والدينيات', gen_random_uuid()),
    ('المتفرقات',                gen_random_uuid()),
    ('المعلقات',                 gen_random_uuid());

  -- (2) Reassign every poem from its old theme to the new theme. At this
  -- point both sets coexist in `themes` (37 rows total). The mapping resolves
  -- new_name → new id and old_name → old id via the UNIQUE themes_name_key.
  WITH mapping(new_name, old_name) AS (VALUES
    ('المديح'::text,                   'مدح'::text),
    ('المديح',                         'جود'),
    ('المديح',                         'سياسية'),
    ('الفخر والحماسة',                 'وطن'),
    ('الفخر والحماسة',                 'صبر'),
    ('الهجاء',                         'هجاء'),
    ('الهجاء',                         'ذم'),
    ('الرثاء',                         'رثاء'),
    ('الرثاء',                         'حزينة'),
    ('النسيب والغزل',                  'غزل'),
    ('النسيب والغزل',                  'رومنسية'),
    ('النسيب والغزل',                  'شوق'),
    ('النسيب والغزل',                  'فراق'),
    ('النسيب والغزل',                  'من'),
    ('العتاب والاعتذار',               'عتاب'),
    ('العتاب والاعتذار',               'اعتذار'),
    ('الحكمة والآداب',                 'حكمة'),
    ('الحكمة والآداب',                 'نصيحة'),
    ('الحكمة والآداب',                 'عدل'),
    ('الزهد والمناجاة والدينيات',      'دينية'),
    ('الزهد والمناجاة والدينيات',      'ابتهال'),
    ('الزهد والمناجاة والدينيات',      'أنشودة'),
    ('الزهد والمناجاة والدينيات',      'رحمة'),
    ('المتفرقات',                      'قصيرة'),
    ('المتفرقات',                      'عامة'),
    ('المتفرقات',                      'غير مصنف'),
    ('المعلقات',                       'معلقة')
  )
  UPDATE poems p
  SET theme_id = t_new.id
  FROM mapping m
  JOIN themes t_new ON t_new.name = m.new_name
  JOIN themes t_old ON t_old.name = m.old_name
  WHERE p.theme_id = t_old.id;

  -- (3) Delete the 27 legacy theme rows.
  DELETE FROM themes WHERE name IN (
    'قصيرة','عامة','مدح','رومنسية','هجاء','حزينة','عتاب','رثاء','غزل','دينية',
    'شوق','من','فراق','حكمة','ذم','نصيحة','وطن','صبر','ابتهال','أنشودة','جود',
    'غير مصنف','رحمة','معلقة','سياسية','اعتذار','عدل'
  );

  -- Post-flight: exactly the 10 expected new themes, nothing else.
  IF (SELECT count(*) FROM themes WHERE name IN (
        'المديح','الفخر والحماسة','الهجاء','الرثاء','النسيب والغزل',
        'العتاب والاعتذار','الحكمة والآداب','الزهد والمناجاة والدينيات',
        'المتفرقات','المعلقات'
      )) <> 10
     OR (SELECT count(*) FROM themes) <> 10 THEN
    RAISE EXCEPTION 'post-flight failed: theme set is not exactly the 10 expected names';
  END IF;

  -- Post-flight: poem count preserved.
  SELECT count(*) INTO v_post_poems_total FROM poems;
  IF v_post_poems_total <> v_pre_poems_total THEN
    RAISE EXCEPTION 'post-flight failed: poem count changed (% -> %)',
      v_pre_poems_total, v_post_poems_total;
  END IF;

  -- Post-flight: every poem still resolves to a theme row.
  SELECT count(*) INTO v_orphans
  FROM poems p
  WHERE NOT EXISTS (SELECT 1 FROM themes t WHERE t.id = p.theme_id);
  IF v_orphans <> 0 THEN
    RAISE EXCEPTION 'post-flight failed: % orphan poem(s) with unresolved theme_id', v_orphans;
  END IF;
END $$;

COMMIT;
