-- scripts/sql/0004_replace_rhymes.sql
-- One-shot migration applied to the 0014 dump to produce the 0015 baseline.
-- Operations (single transaction):
--   1. Pre-flight: assert the legacy 32-pattern rhymes layout is present.
--   2. DROP the rhyme_stats view (depends on rhymes.pattern).
--   3. UPDATE poems SET rhyme_id = NULL (about to lose the referent).
--   4. DROP and recreate the rhymes table with (id, letter, slug, name).
--   5. INSERT the 36 canonical qafiyah-letter rows with deterministic ids.
--   6. setval the identity sequence to 36.
--   7. CREATE VIEW rhyme_stats with the new column shape.
--
-- A separate Bun script (scripts/extract-rhymes.ts) repopulates
-- poems.rhyme_id from poems.content after this file runs.
--
-- NOT idempotent: re-running on already-migrated data raises an exception
-- via the pre-flight guard below.
BEGIN;

DO $$
DECLARE
  v_legacy_count integer;
  v_has_pattern  integer;
BEGIN
  -- Pre-flight: legacy layout has 32 rows and a `pattern` column.
  SELECT count(*) INTO v_has_pattern
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'rhymes' AND column_name = 'pattern';
  IF v_has_pattern <> 1 THEN
    RAISE EXCEPTION 'pre-flight failed: rhymes.pattern column not found (already migrated?)';
  END IF;

  SELECT count(*) INTO v_legacy_count FROM rhymes;
  IF v_legacy_count <> 32 THEN
    RAISE EXCEPTION 'pre-flight failed: expected 32 legacy rhyme rows, found %', v_legacy_count;
  END IF;
END $$;

-- Drop the stats view first; it selects rhymes.pattern.
DROP VIEW IF EXISTS rhyme_stats;

-- Drop FK values; the script that re-derives them runs after this file.
UPDATE poems SET rhyme_id = NULL;

-- Replace the table entirely. CASCADE drops the FK from poems.rhyme_id,
-- which we re-add below.
DROP TABLE rhymes CASCADE;

CREATE TABLE rhymes (
  id     smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  letter text     NOT NULL UNIQUE,
  slug   text     NOT NULL UNIQUE,
  name   text     NOT NULL
);

-- Re-add the FK that CASCADE dropped.
ALTER TABLE poems
  ADD CONSTRAINT poems_rhyme_id_fkey
  FOREIGN KEY (rhyme_id) REFERENCES rhymes(id);

-- Seed the 36 canonical qafiyah letters. Explicit ids for determinism
-- across dump cycles (apps/web/src/constants.ts RHYMES_OPTIONS pins these).
INSERT INTO rhymes (id, letter, slug, name) VALUES
  (1,  'ا', 'alef',           'ألف'),
  (2,  'أ', 'alef-maftuha',   'ألف مفتوحة'),
  (3,  'إ', 'alef-maksura',   'ألف مكسورة'),
  (4,  'آ', 'alef-mamduda',   'ألف مدودة'),
  (5,  'ى', 'alef-maqsura',   'ألف مقصورة'),
  (6,  'ء', 'hamza',          'همزة'),
  (7,  'ؤ', 'hamza-madmuma',  'همزة مضمومة'),
  (8,  'ئ', 'hamza-maksura',  'همزة مكسورة'),
  (9,  'ة', 'taa-marbuta',    'تاء مربوطة'),
  (10, 'ب', 'baa',            'باء'),
  (11, 'ت', 'taa',            'تاء'),
  (12, 'ث', 'thaa',           'ثاء'),
  (13, 'ج', 'jeem',           'جيم'),
  (14, 'ح', 'hha',            'حاء'),
  (15, 'خ', 'khaa',           'خاء'),
  (16, 'د', 'dal',            'دال'),
  (17, 'ذ', 'dhal',           'ذال'),
  (18, 'ر', 'raa',            'راء'),
  (19, 'ز', 'zay',            'زاي'),
  (20, 'س', 'seen',           'سين'),
  (21, 'ش', 'sheen',          'شين'),
  (22, 'ص', 'sad',            'صاد'),
  (23, 'ض', 'dad',            'ضاد'),
  (24, 'ط', 'tta',            'طاء'),
  (25, 'ظ', 'dhha',           'ظاء'),
  (26, 'ع', 'ayn',            'عين'),
  (27, 'غ', 'ghayn',          'غين'),
  (28, 'ف', 'faa',            'فاء'),
  (29, 'ق', 'qaf',            'قاف'),
  (30, 'ك', 'kaf',            'كاف'),
  (31, 'ل', 'lam',            'لام'),
  (32, 'م', 'meem',           'ميم'),
  (33, 'ن', 'noon',           'نون'),
  (34, 'ه', 'haa',            'هاء'),
  (35, 'و', 'waw',            'واو'),
  (36, 'ي', 'yaa',            'ياء');

-- Push the sequence past 36 so future inserts don't collide.
SELECT setval(pg_get_serial_sequence('rhymes', 'id'),
              (SELECT max(id) FROM rhymes));

-- Recreate the stats view with the new shape. `pattern` becomes `name`.
CREATE VIEW rhyme_stats AS
SELECT
  r.id                                          AS id,
  r.letter                                      AS letter,
  r.slug                                        AS slug,
  r.name                                        AS name,
  count(p.id)::int                              AS poems_count,
  count(DISTINCT p.poet_id)::int                AS poets_count
FROM rhymes r
LEFT JOIN poems p ON p.rhyme_id = r.id
GROUP BY r.id, r.letter, r.slug, r.name;

-- Post-flight: must have exactly 36 letter rows.
DO $$
DECLARE
  v_count integer;
BEGIN
  SELECT count(*) INTO v_count FROM rhymes;
  IF v_count <> 36 THEN
    RAISE EXCEPTION 'post-flight failed: expected 36 rhyme rows, found %', v_count;
  END IF;
END $$;

COMMIT;
