-- scripts/sql/0008_extract_collections.sql
-- One-shot migration applied to the 0020 dump to produce the 0021 baseline.
-- Extracts المعلقات from themes into a new `collections` taxonomy:
--   1. Create `collections` table (mirror of `themes` shape).
--   2. Add nullable `poems.collection_id` FK.
--   3. Insert the المعلقات collection.
--   4. For each of the 10 المعلقات-theme poems: set collection_id to the new
--      collection and reassign theme_id per a poet → theme mapping
--      (المعلقات poets each get a topically-appropriate theme).
--   5. Delete the المعلقات theme row.
--   6. Create `collection_stats` view (mirror of `theme_stats`).
--   7. Drop & recreate `poem_full_data` view to expose the
--      new collection columns via LEFT JOIN (collection_id is nullable).
--
-- NOT idempotent: re-running on already-migrated data raises an exception
-- via the pre-flight guards below.
BEGIN;

DO $$
DECLARE
  v_has_collections    integer;
  v_has_collection_id  integer;
  v_muallaqat_id       integer;
  v_muallaqat_poems    integer;
  v_fallback_count     integer;
BEGIN
  -- Pre-flight: collections table must not exist.
  SELECT count(*) INTO v_has_collections
  FROM information_schema.tables
  WHERE table_schema = 'public' AND table_name = 'collections';
  IF v_has_collections <> 0 THEN
    RAISE EXCEPTION 'pre-flight failed: public.collections already exists (already migrated?)';
  END IF;

  -- Pre-flight: poems.collection_id must not exist.
  SELECT count(*) INTO v_has_collection_id
  FROM information_schema.columns
  WHERE table_schema = 'public' AND table_name = 'poems' AND column_name = 'collection_id';
  IF v_has_collection_id <> 0 THEN
    RAISE EXCEPTION 'pre-flight failed: poems.collection_id already exists (already migrated?)';
  END IF;

  -- Pre-flight: المعلقات theme exists with exactly 10 poems.
  SELECT id INTO v_muallaqat_id FROM themes WHERE name = 'المعلقات';
  IF v_muallaqat_id IS NULL THEN
    RAISE EXCEPTION 'pre-flight failed: theme "المعلقات" not found';
  END IF;
  SELECT count(*) INTO v_muallaqat_poems FROM poems WHERE theme_id = v_muallaqat_id;
  IF v_muallaqat_poems <> 10 THEN
    RAISE EXCEPTION 'pre-flight failed: expected 10 poems under theme "المعلقات", found %', v_muallaqat_poems;
  END IF;

  -- Pre-flight: the 4 fallback themes exist.
  SELECT count(*) INTO v_fallback_count
  FROM themes WHERE name IN ('النسيب', 'الحكمة', 'الحماسة', 'المديح');
  IF v_fallback_count <> 4 THEN
    RAISE EXCEPTION 'pre-flight failed: expected 4 fallback themes, found %', v_fallback_count;
  END IF;
END $$;

-- (1) Create the collections table.
CREATE TABLE public.collections (
  id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  slug uuid NOT NULL UNIQUE
);

-- (2) Add the nullable FK on poems.
ALTER TABLE public.poems
  ADD COLUMN collection_id integer NULL
  REFERENCES public.collections(id);

-- (3) Insert المعلقات collection.
INSERT INTO public.collections (name, slug) VALUES ('المعلقات', gen_random_uuid());

-- (4) Reassign theme_id and set collection_id for the 10 المعلقات poems.
DO $$
DECLARE
  v_muallaqat_id      integer := (SELECT id FROM themes WHERE name = 'المعلقات');
  v_new_collection_id integer := (SELECT id FROM collections WHERE name = 'المعلقات');
  v_updated           integer;
BEGIN
  WITH mapping(poet_name, new_theme_name) AS (VALUES
    ('امرؤ القيس'::text,        'النسيب'::text),
    ('طرفة بن العبد',           'الحكمة'),
    ('زهير بن أبي سلمى',        'الحكمة'),
    ('لبيد بن ربيعة',           'الحماسة'),
    ('عمرو بن كلثوم',           'الحماسة'),
    ('عنترة بن شداد',           'الحماسة'),
    ('الحارث بن حلزة',          'الحماسة'),
    ('النابغة الذبياني',        'المديح'),
    ('الأعشى',                  'المديح'),
    ('عبيد بن الأبرص',          'الحكمة')
  )
  UPDATE poems p
  SET theme_id      = t_new.id,
      collection_id = v_new_collection_id
  FROM mapping m
  JOIN poets pt  ON pt.name    = m.poet_name
  JOIN themes t_new ON t_new.name = m.new_theme_name
  WHERE p.poet_id = pt.id
    AND p.theme_id = v_muallaqat_id;

  GET DIAGNOSTICS v_updated = ROW_COUNT;
  IF v_updated <> 10 THEN
    RAISE EXCEPTION 'reassignment failed: expected 10 row updates, got %', v_updated;
  END IF;
END $$;

-- (5) Delete the now-empty المعلقات theme row.
DELETE FROM public.themes WHERE name = 'المعلقات';

-- (6) Create collection_stats view (mirrors theme_stats).
CREATE VIEW public.collection_stats
  WITH (security_invoker=on)
  AS
  SELECT c.id,
         c.name,
         c.slug,
         count(DISTINCT p.id)  AS poems_count,
         count(DISTINCT pt.id) AS poets_count
    FROM collections c
    LEFT JOIN poems p  ON c.id = p.collection_id
    LEFT JOIN poets pt ON p.poet_id = pt.id
   GROUP BY c.id, c.name, c.slug;

-- (7) Recreate poem_full_data with the two new columns.
DROP VIEW IF EXISTS public.poem_full_data;
CREATE VIEW public.poem_full_data AS
SELECT p.slug,
       p.title,
       p.content,
       p.verse_count,
       po.name AS poet_name,
       po.slug AS poet_slug,
       m.name  AS meter_name,
       t.name  AS theme_name,
       e.name  AS era_name,
       e.slug  AS era_slug,
       c.name  AS collection_name,
       c.slug  AS collection_slug
  FROM poems p
  JOIN poets po       ON p.poet_id = po.id
  JOIN meters m       ON p.meter_id = m.id
  JOIN themes t       ON p.theme_id = t.id
  JOIN eras e         ON po.era_id = e.id
  LEFT JOIN collections c ON p.collection_id = c.id;

-- Post-flight assertions.
DO $$
DECLARE
  v_theme_count          integer;
  v_muallaqat_theme_left integer;
  v_collection_count     integer;
  v_muallaqat_coll_count integer;
  v_linked_poems         integer;
  v_orphan_themes        integer;
  v_orphan_collections   integer;
BEGIN
  SELECT count(*) INTO v_theme_count FROM themes;
  IF v_theme_count <> 9 THEN
    RAISE EXCEPTION 'post-flight failed: expected 9 themes, found %', v_theme_count;
  END IF;

  SELECT count(*) INTO v_muallaqat_theme_left FROM themes WHERE name = 'المعلقات';
  IF v_muallaqat_theme_left <> 0 THEN
    RAISE EXCEPTION 'post-flight failed: المعلقات theme still present';
  END IF;

  SELECT count(*) INTO v_collection_count FROM collections;
  IF v_collection_count <> 1 THEN
    RAISE EXCEPTION 'post-flight failed: expected 1 collection, found %', v_collection_count;
  END IF;

  SELECT count(*) INTO v_muallaqat_coll_count FROM collections WHERE name = 'المعلقات';
  IF v_muallaqat_coll_count <> 1 THEN
    RAISE EXCEPTION 'post-flight failed: المعلقات collection not present';
  END IF;

  SELECT count(*) INTO v_linked_poems FROM poems WHERE collection_id IS NOT NULL;
  IF v_linked_poems <> 10 THEN
    RAISE EXCEPTION 'post-flight failed: expected 10 poems linked to a collection, found %', v_linked_poems;
  END IF;

  SELECT count(*) INTO v_orphan_themes
  FROM poems p WHERE NOT EXISTS (SELECT 1 FROM themes t WHERE t.id = p.theme_id);
  IF v_orphan_themes <> 0 THEN
    RAISE EXCEPTION 'post-flight failed: % poem(s) with unresolved theme_id', v_orphan_themes;
  END IF;

  SELECT count(*) INTO v_orphan_collections
  FROM poems p WHERE p.collection_id IS NOT NULL
               AND NOT EXISTS (SELECT 1 FROM collections c WHERE c.id = p.collection_id);
  IF v_orphan_collections <> 0 THEN
    RAISE EXCEPTION 'post-flight failed: % poem(s) with unresolved collection_id', v_orphan_collections;
  END IF;
END $$;

COMMIT;
